// Dữ liệu mẫu biên soạn theo bộ đề 200 câu thi lý thuyết GPLX xe máy tại Việt Nam.
// A1: 40 câu, A2: 12 câu, A3: 8 câu — phủ đủ 4 chủ đề, có câu điểm liệt và ảnh biển báo.
// Ảnh biển báo là file SVG tĩnh phục vụ từ frontend: /images/signs/<tên>.svg

const licenseClasses = [
  {
    code: 'A1',
    name: 'Hạng A1 - Xe mô tô hai bánh 50cc đến dưới 175cc',
    description: 'Dành cho xe mô tô hai bánh có dung tích xi-lanh từ 50cc đến dưới 175cc.',
    examConfig: { numQuestions: 25, durationMinutes: 19, passScore: 21 },
  },
  {
    code: 'A2',
    name: 'Hạng A2 - Xe mô tô hai bánh từ 175cc trở lên',
    description: 'Dành cho xe mô tô hai bánh có dung tích xi-lanh từ 175cc trở lên.',
    examConfig: { numQuestions: 25, durationMinutes: 19, passScore: 23 },
  },
  {
    code: 'A3',
    name: 'Hạng A3 - Xe mô tô ba bánh',
    description: 'Dành cho xe mô tô ba bánh và các loại xe hạng A1.',
    examConfig: { numQuestions: 25, durationMinutes: 19, passScore: 21 },
  },
];

const categories = [
  { name: 'Khái niệm và quy tắc', description: 'Khái niệm, quy tắc giao thông đường bộ.' },
  { name: 'Biển báo giao thông', description: 'Nhận biết ý nghĩa các biển báo hiệu đường bộ.' },
  { name: 'Sa hình', description: 'Xử lý tình huống qua các bài sa hình.' },
  { name: 'Đạo đức và văn hóa giao thông', description: 'Đạo đức người lái xe, văn hóa giao thông.' },
];

const SIGN = (file) => `/images/signs/${file}`;

const questions = [
  /* ================= A1 — KHÁI NIỆM VÀ QUY TẮC (14 câu) ================= */
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: '"Phương tiện giao thông cơ giới đường bộ" gồm những loại nào dưới đây?',
    options: [
      'Xe ô tô, máy kéo, rơ moóc; xe mô tô hai bánh, ba bánh; xe gắn máy và các loại xe tương tự.',
      'Xe đạp, xe xích lô, xe lăn dùng cho người khuyết tật.',
      'Xe máy chuyên dùng phục vụ thi công.',
    ],
    correctIndex: 0,
    explanation: 'Phương tiện cơ giới gồm ô tô, máy kéo, rơ moóc, mô tô hai - ba bánh, xe gắn máy và xe tương tự.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: '"Làn đường" là gì?',
    options: [
      'Là phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.',
      'Là phần đường xe chạy trên đường một chiều.',
      'Là phần mặt đường dành cho người đi bộ.',
    ],
    correctIndex: 0,
    explanation: 'Làn đường là một phần của phần đường xe chạy, chia theo chiều dọc, đủ rộng cho xe chạy an toàn.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người điều khiển xe mô tô hai bánh có được sử dụng ô (dù), điện thoại di động khi đang chạy xe không?',
    options: [
      'Được sử dụng khi thật cần thiết.',
      'Không được sử dụng.',
      'Chỉ được sử dụng ở đường vắng.',
    ],
    correctIndex: 1,
    explanation: 'Nghiêm cấm người lái mô tô, xe gắn máy sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ trợ thính) khi lái xe.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người điều khiển xe mô tô, xe gắn máy mà trong máu hoặc hơi thở có nồng độ cồn thì bị xử lý như thế nào?',
    options: [
      'Được lái xe nếu nồng độ cồn thấp dưới mức cho phép.',
      'Bị nghiêm cấm điều khiển phương tiện.',
      'Chỉ bị nhắc nhở, cảnh cáo.',
    ],
    correctIndex: 1,
    explanation: 'Luật nghiêm cấm tuyệt đối điều khiển phương tiện khi trong máu hoặc hơi thở có nồng độ cồn.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người đủ bao nhiêu tuổi trở lên thì được điều khiển xe mô tô hai bánh có dung tích xi-lanh từ 50cc đến dưới 175cc?',
    options: ['16 tuổi.', '18 tuổi.', '20 tuổi.'],
    correctIndex: 1,
    explanation: 'Đủ 18 tuổi được cấp GPLX hạng A1 điều khiển xe mô tô 50cc đến dưới 175cc.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Trên đường bộ, người lái xe mô tô hai bánh được chở tối đa mấy người?',
    options: [
      'Một người, không kể người lái.',
      'Hai người lớn trong mọi trường hợp.',
      'Một người; chở tối đa hai người trong trường hợp chở người bệnh đi cấp cứu, trẻ em dưới 14 tuổi, áp giải người phạm pháp.',
    ],
    correctIndex: 2,
    explanation: 'Mô tô chỉ được chở 1 người; được chở 2 người khi chở người bệnh cấp cứu, trẻ dưới 14 tuổi hoặc áp giải người phạm pháp.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Khi muốn chuyển hướng, người lái xe phải làm gì để bảo đảm an toàn?',
    options: [
      'Quan sát gương, giảm tốc độ, bật tín hiệu báo hướng rẽ và chỉ chuyển hướng khi bảo đảm an toàn.',
      'Tăng tốc độ để chuyển hướng nhanh chóng.',
      'Chuyển hướng ngay, các xe khác phải nhường.',
    ],
    correctIndex: 0,
    explanation: 'Trước khi chuyển hướng phải giảm tốc độ, có tín hiệu báo hướng rẽ và nhường đường theo quy định.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Trong khu vực đông dân cư, xe mô tô, xe gắn máy được chạy với tốc độ tối đa bao nhiêu trên đường hai chiều không có dải phân cách giữa?',
    options: ['40 km/h.', '50 km/h.', '60 km/h.'],
    correctIndex: 1,
    explanation: 'Trong khu đông dân cư, đường hai chiều không dải phân cách: tối đa 50 km/h với mô tô (xe gắn máy tối đa 40 km/h).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người ngồi trên xe mô tô hai bánh, xe gắn máy khi tham gia giao thông phải đội gì?',
    options: [
      'Mũ bảo hiểm có cài quai đúng quy cách.',
      'Mũ vải hoặc mũ lưỡi trai.',
      'Không bắt buộc nếu đi đoạn đường ngắn.',
    ],
    correctIndex: 0,
    explanation: 'Người lái và người ngồi sau mô tô, xe gắn máy bắt buộc đội mũ bảo hiểm đạt chuẩn, cài quai đúng quy cách.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Khi điều khiển xe chạy trên đường, người lái xe phải mang theo những giấy tờ gì?',
    options: [
      'Chỉ cần giấy phép lái xe.',
      'Giấy phép lái xe; đăng ký xe; giấy chứng nhận bảo hiểm trách nhiệm dân sự còn hiệu lực.',
      'Chỉ cần chứng minh nhân dân/căn cước công dân.',
    ],
    correctIndex: 1,
    explanation: 'Phải mang GPLX, đăng ký xe và bảo hiểm trách nhiệm dân sự bắt buộc còn hiệu lực.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Tại nơi có vạch kẻ đường dành cho người đi bộ, người điều khiển phương tiện phải xử lý như thế nào?',
    options: [
      'Nhấn còi liên tục để người đi bộ nhường đường.',
      'Quan sát, giảm tốc độ và nhường đường cho người đi bộ.',
      'Tăng tốc vượt qua trước khi người đi bộ tới.',
    ],
    correctIndex: 1,
    explanation: 'Phải quan sát, giảm tốc độ, nhường đường cho người đi bộ tại nơi có vạch kẻ đường dành cho họ.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Xe mô tô, xe gắn máy có được kéo, đẩy xe khác hoặc vật khác khi tham gia giao thông không?',
    options: [
      'Được phép nếu vật kéo nhẹ.',
      'Không được kéo, đẩy xe khác, vật khác; không mang vác cồng kềnh.',
      'Được phép khi đường vắng.',
    ],
    correctIndex: 1,
    explanation: 'Cấm người lái mô tô, xe gắn máy kéo/đẩy xe khác, mang vác vật cồng kềnh gây mất an toàn.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Khi vượt xe khác, người lái xe phải thực hiện như thế nào?',
    options: [
      'Vượt về bên phải xe bị vượt trong mọi trường hợp.',
      'Báo hiệu bằng đèn hoặc còi, vượt về bên trái khi quan sát thấy an toàn và xe trước không có tín hiệu vượt xe khác.',
      'Tăng tốc vượt ngay khi thấy xe trước đi chậm.',
    ],
    correctIndex: 1,
    explanation: 'Vượt xe phải báo hiệu, vượt về bên trái và chỉ vượt khi bảo đảm an toàn, không có chướng ngại phía trước.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Hành vi lạng lách, đánh võng trên đường bộ bị xử lý như thế nào?',
    options: [
      'Bị nghiêm cấm.',
      'Được phép ở nơi đường rộng, vắng người.',
      'Chỉ cấm với xe ô tô.',
    ],
    correctIndex: 0,
    explanation: 'Điều khiển xe lạng lách, đánh võng là hành vi bị nghiêm cấm, gây nguy hiểm cho người tham gia giao thông.',
    isCritical: true,
  },

  /* ================= A1 — BIỂN BÁO GIAO THÔNG (12 câu, có ảnh) ================= */
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình có ý nghĩa gì?',
    imageUrl: SIGN('cam-nguoc-chieu.svg'),
    options: [
      'Cấm đi ngược chiều.',
      'Cấm dừng xe và đỗ xe.',
      'Đường một chiều được phép đi.',
    ],
    correctIndex: 0,
    explanation: 'Biển tròn nền đỏ, vạch trắng nằm ngang là biển "Cấm đi ngược chiều" (P.102).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình có ý nghĩa gì?',
    imageUrl: SIGN('toc-do-toi-da-40.svg'),
    options: [
      'Tốc độ tối thiểu cho phép là 40 km/h.',
      'Tốc độ tối đa cho phép là 40 km/h.',
      'Cách bến xe phía trước 40 mét.',
    ],
    correctIndex: 1,
    explanation: 'Biển tròn viền đỏ nền trắng ghi số 40 là biển "Tốc độ tối đa cho phép" 40 km/h (P.127).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình có ý nghĩa gì?',
    imageUrl: SIGN('cam-dung-do.svg'),
    options: [
      'Cấm đỗ xe, được phép dừng.',
      'Cấm dừng xe và đỗ xe.',
      'Nơi đỗ xe dành riêng.',
    ],
    correctIndex: 1,
    explanation: 'Biển nền xanh viền đỏ có hai vạch chéo đỏ là biển "Cấm dừng xe và đỗ xe" (P.130).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình cấm loại phương tiện nào?',
    imageUrl: SIGN('cam-mo-to.svg'),
    options: [
      'Cấm xe đạp.',
      'Cấm xe mô tô.',
      'Cấm tất cả xe cơ giới.',
    ],
    correctIndex: 1,
    explanation: 'Biển viền đỏ có hình xe mô tô gạch chéo là biển "Cấm xe mô tô" (P.104).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình báo hiệu điều gì?',
    imageUrl: SIGN('giao-nhau-cung-cap.svg'),
    options: [
      'Giao nhau với đường ưu tiên.',
      'Giao nhau của các đường cùng cấp.',
      'Đường hai chiều phía trước.',
    ],
    correctIndex: 1,
    explanation: 'Biển tam giác vàng có dấu "+" đen là biển "Giao nhau của các đường cùng cấp" (W.205).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình yêu cầu người lái xe làm gì?',
    imageUrl: SIGN('nhuong-duong.svg'),
    options: [
      'Dừng lại hẳn trước vạch dừng.',
      'Nhường đường cho xe trên đường ưu tiên đi trước.',
      'Được quyền ưu tiên đi trước.',
    ],
    correctIndex: 1,
    explanation: 'Biển tam giác ngược viền đỏ là biển "Giao nhau với đường ưu tiên" (W.208) — phải nhường đường.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình cảnh báo điều gì?',
    imageUrl: SIGN('tre-em.svg'),
    options: [
      'Gần trường học, đoạn đường thường có trẻ em đi qua.',
      'Cấm trẻ em qua đường.',
      'Khu vui chơi dành cho trẻ em.',
    ],
    correctIndex: 0,
    explanation: 'Biển tam giác vàng có hình trẻ em là biển cảnh báo "Trẻ em" (W.225) — giảm tốc độ, chú ý quan sát.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình cảnh báo điều gì?',
    imageUrl: SIGN('cho-ngoat-trai.svg'),
    options: [
      'Chỗ ngoặt nguy hiểm vòng bên trái.',
      'Hướng đi thẳng phải theo.',
      'Đường bị hẹp bên trái.',
    ],
    correctIndex: 0,
    explanation: 'Biển tam giác vàng có mũi tên cong sang trái là biển "Chỗ ngoặt nguy hiểm vòng bên trái" (W.201a).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình yêu cầu điều gì?',
    imageUrl: SIGN('hieu-lenh-di-thang.svg'),
    options: [
      'Chỉ được đi thẳng.',
      'Được đi thẳng và rẽ phải.',
      'Đường một chiều.',
    ],
    correctIndex: 0,
    explanation: 'Biển tròn xanh có mũi tên thẳng đứng là biển hiệu lệnh "Các xe chỉ được đi thẳng" (R.301a).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình báo hiệu điều gì?',
    imageUrl: SIGN('vong-xuyen.svg'),
    options: [
      'Nơi giao nhau chạy theo vòng xuyến, phải nhường đường cho xe đi bên trái.',
      'Cấm quay đầu xe.',
      'Được phép quay đầu tại nơi giao nhau.',
    ],
    correctIndex: 0,
    explanation: 'Biển tròn xanh có mũi tên vòng là biển "Nơi giao nhau chạy theo vòng xuyến" (R.303).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình chỉ dẫn điều gì?',
    imageUrl: SIGN('duong-nguoi-di-bo.svg'),
    options: [
      'Đường dành cho người đi bộ sang ngang.',
      'Cấm người đi bộ.',
      'Đường cụt phía trước.',
    ],
    correctIndex: 0,
    explanation: 'Biển vuông nền xanh có hình người đi bộ trên vạch là biển chỉ dẫn "Đường người đi bộ sang ngang" (I.423).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình cấm hành vi nào?',
    imageUrl: SIGN('cam-re-trai.svg'),
    options: [
      'Cấm rẽ trái.',
      'Cấm quay đầu xe.',
      'Cấm rẽ phải.',
    ],
    correctIndex: 0,
    explanation: 'Biển viền đỏ có mũi tên rẽ trái bị gạch chéo là biển "Cấm rẽ trái" (P.123a).',
    isCritical: false,
  },

  /* ================= A1 — SA HÌNH (8 câu) ================= */
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Tại nơi đường giao nhau không có báo hiệu đi theo vòng xuyến, các xe phải nhường đường như thế nào?',
    options: [
      'Nhường đường cho xe đi đến từ bên phải.',
      'Nhường đường cho xe đi đến từ bên trái.',
      'Xe nào nhanh hơn được đi trước.',
    ],
    correctIndex: 0,
    explanation: 'Tại nơi giao nhau cùng cấp không vòng xuyến: nhường xe đến từ bên phải.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Tại nơi giao nhau có báo hiệu đi theo vòng xuyến, phải nhường đường cho xe nào?',
    options: [
      'Xe đi đến từ bên phải.',
      'Xe đi đến từ bên trái.',
      'Xe có tốc độ cao hơn.',
    ],
    correctIndex: 1,
    explanation: 'Vào vòng xuyến phải nhường đường cho xe đi đến từ bên trái (xe đang trong vòng xuyến).',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Khi có xe ưu tiên đang phát tín hiệu ưu tiên đi làm nhiệm vụ, người tham gia giao thông phải làm gì?',
    options: [
      'Nhanh chóng giảm tốc độ, tránh hoặc dừng lại sát lề đường bên phải để nhường đường.',
      'Tiếp tục đi bình thường nếu đang đi đúng làn.',
      'Chỉ nhường khi xe ưu tiên nhấn còi.',
    ],
    correctIndex: 0,
    explanation: 'Mọi phương tiện phải giảm tốc, tránh hoặc dừng sát lề phải nhường đường cho xe ưu tiên.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Thứ tự các xe được quyền ưu tiên đi trước nào dưới đây là đúng?',
    options: [
      'Xe chữa cháy - xe quân sự, công an - xe cứu thương - xe hộ đê.',
      'Xe cứu thương - xe chữa cháy - xe quân sự.',
      'Xe hộ đê - xe chữa cháy - xe cứu thương.',
    ],
    correctIndex: 0,
    explanation: 'Thứ tự ưu tiên: chữa cháy → quân sự/công an → cứu thương → hộ đê/khắc phục thiên tai → đoàn xe tang.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Trên đoạn đường hẹp có chướng ngại vật phía trước bên làn của mình, người lái xe phải xử lý thế nào khi có xe ngược chiều đi tới?',
    options: [
      'Nhường đường cho xe ngược chiều đi trước rồi mới vượt chướng ngại vật.',
      'Tăng tốc vượt chướng ngại vật trước xe ngược chiều.',
      'Nhấn còi yêu cầu xe ngược chiều dừng lại.',
    ],
    correctIndex: 0,
    explanation: 'Bên có chướng ngại vật phải nhường đường cho xe đi chiều ngược lại.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Khi đèn tín hiệu màu vàng bật sáng, người điều khiển phương tiện phải làm gì?',
    options: [
      'Dừng lại trước vạch dừng, trừ trường hợp đã đi quá vạch dừng thì được đi tiếp.',
      'Tăng tốc vượt qua giao lộ trước khi đèn đỏ.',
      'Được đi tiếp như đèn xanh.',
    ],
    correctIndex: 0,
    explanation: 'Đèn vàng: dừng trước vạch dừng; nếu đã vượt quá vạch thì được đi tiếp để tránh phanh gấp nguy hiểm.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Tại nơi giao nhau giữa đường không ưu tiên và đường ưu tiên, xe từ đường không ưu tiên phải làm gì?',
    options: [
      'Nhường đường cho xe đi trên đường ưu tiên từ bất kỳ hướng nào tới.',
      'Chỉ nhường xe bên phải.',
      'Được đi trước nếu tới giao lộ trước.',
    ],
    correctIndex: 0,
    explanation: 'Xe từ đường không ưu tiên/đường nhánh phải nhường mọi xe trên đường ưu tiên/đường chính.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Sa hình',
    content: 'Khi gặp hiệu lệnh của người điều khiển giao thông trái với đèn tín hiệu, người lái xe phải chấp hành theo cái nào?',
    options: [
      'Đèn tín hiệu giao thông.',
      'Hiệu lệnh của người điều khiển giao thông.',
      'Biển báo hiệu đường bộ.',
    ],
    correctIndex: 1,
    explanation: 'Thứ tự hiệu lực: người điều khiển giao thông > đèn tín hiệu > biển báo > vạch kẻ đường.',
    isCritical: true,
  },

  /* ================= A1 — ĐẠO ĐỨC VÀ VĂN HÓA (6 câu) ================= */
  {
    classCode: 'A1',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Người có văn hóa giao thông khi điều khiển xe cơ giới cần thể hiện như thế nào?',
    options: [
      'Tự giác chấp hành luật, nhường nhịn và giúp đỡ người khác khi tham gia giao thông.',
      'Đi nhanh nhất có thể để tiết kiệm thời gian.',
      'Chỉ chấp hành luật khi có cảnh sát giao thông.',
    ],
    correctIndex: 0,
    explanation: 'Văn hóa giao thông là tự giác chấp hành pháp luật, ứng xử nhường nhịn, giúp đỡ người khác.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Khi xảy ra tai nạn giao thông, những người có mặt tại hiện trường có trách nhiệm gì?',
    options: [
      'Nhanh chóng rời khỏi hiện trường để tránh liên lụy.',
      'Bảo vệ hiện trường, giúp đỡ cứu chữa người bị nạn và báo tin cho cơ quan công an hoặc y tế gần nhất.',
      'Chỉ đứng xem, việc cứu người là của cơ quan chức năng.',
    ],
    correctIndex: 1,
    explanation: 'Người có mặt phải bảo vệ hiện trường, cứu giúp người bị nạn, báo tin cho cơ quan chức năng.',
    isCritical: true,
  },
  {
    classCode: 'A1',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Khi đi qua khu vực trường học vào giờ tan học, người lái xe nên xử lý như thế nào?',
    options: [
      'Giảm tốc độ, chú ý quan sát, sẵn sàng nhường đường cho học sinh.',
      'Nhấn còi liên tục để học sinh tránh xa.',
      'Giữ nguyên tốc độ vì đang đi đúng phần đường.',
    ],
    correctIndex: 0,
    explanation: 'Khu vực trường học cần giảm tốc, quan sát kỹ vì trẻ em có thể bất ngờ băng qua đường.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Người lái xe cố tình không phân biệt làn đường, vạch phân làn, phóng nhanh vượt ẩu thể hiện điều gì?',
    options: [
      'Thiếu văn hóa giao thông và ý thức chấp hành pháp luật kém.',
      'Kỹ năng lái xe điêu luyện.',
      'Sự tự tin cần thiết khi lái xe.',
    ],
    correctIndex: 0,
    explanation: 'Đó là biểu hiện thiếu văn hóa, coi thường pháp luật và tính mạng người khác.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Trời mưa to, đoạn đường ngập nước, người lái xe mô tô nên xử lý như thế nào?',
    options: [
      'Đi chậm, quan sát, giữ khoảng cách an toàn; không đi vào chỗ ngập sâu, chảy xiết.',
      'Tăng ga vượt nhanh qua đoạn ngập.',
      'Bám sát xe phía trước để đi theo.',
    ],
    correctIndex: 0,
    explanation: 'Đường ngập phải đi chậm, tránh chỗ ngập sâu, nước chảy xiết để bảo đảm an toàn.',
    isCritical: false,
  },
  {
    classCode: 'A1',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Việc nhường đường cho xe buýt đang ra/vào bến thể hiện điều gì?',
    options: [
      'Văn hóa giao thông và sự ưu tiên cho phương tiện công cộng.',
      'Sự yếu kém khi tham gia giao thông.',
      'Chỉ bắt buộc với xe ô tô con.',
    ],
    correctIndex: 0,
    explanation: 'Nhường xe buýt ra vào bến vừa là quy định vừa thể hiện văn hóa, hỗ trợ giao thông công cộng.',
    isCritical: false,
  },

  /* ================= A2 (12 câu) ================= */
  {
    classCode: 'A2',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Giấy phép lái xe hạng A2 cấp cho người điều khiển loại xe nào?',
    options: [
      'Xe mô tô hai bánh có dung tích xi-lanh từ 175cc trở lên và các loại xe quy định cho hạng A1.',
      'Chỉ xe mô tô ba bánh.',
      'Xe mô tô hai bánh dưới 175cc.',
    ],
    correctIndex: 0,
    explanation: 'A2: mô tô hai bánh từ 175cc trở lên, bao gồm cả quyền điều khiển xe hạng A1.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người điều khiển xe mô tô phân khối lớn cần giữ khoảng cách với xe phía trước như thế nào?',
    options: [
      'Giữ khoảng cách an toàn tùy tốc độ và điều kiện mặt đường, thời tiết.',
      'Càng gần càng tốt để dễ vượt.',
      'Không cần giữ khoảng cách nếu phanh tốt.',
    ],
    correctIndex: 0,
    explanation: 'Phải giữ khoảng cách an toàn phù hợp tốc độ, mật độ và điều kiện đường sá, thời tiết.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Ngoài khu vực đông dân cư, xe mô tô được chạy tốc độ tối đa bao nhiêu trên đường hai chiều không có dải phân cách giữa?',
    options: ['60 km/h.', '70 km/h.', '80 km/h.'],
    correctIndex: 1,
    explanation: 'Ngoài khu đông dân cư, đường hai chiều không dải phân cách: mô tô tối đa 70 km/h.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người điều khiển mô tô phân khối lớn sử dụng rượu bia rồi lái xe sẽ bị xử lý thế nào?',
    options: [
      'Bị nghiêm cấm tuyệt đối, xử phạt nặng và có thể bị tước GPLX.',
      'Được phép nếu uống ít.',
      'Chỉ bị nhắc nhở lần đầu.',
    ],
    correctIndex: 0,
    explanation: 'Cấm tuyệt đối lái xe khi có nồng độ cồn; vi phạm bị phạt nặng, tước GPLX.',
    isCritical: true,
  },
  {
    classCode: 'A2',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình có ý nghĩa gì?',
    imageUrl: SIGN('cam-mo-to.svg'),
    options: [
      'Cấm xe mô tô đi vào.',
      'Cấm xe gắn máy dưới 50cc.',
      'Chỉ dẫn đường dành cho mô tô.',
    ],
    correctIndex: 0,
    explanation: 'Biển "Cấm xe mô tô" — áp dụng với cả mô tô phân khối lớn.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình yêu cầu gì với người lái mô tô phân khối lớn?',
    imageUrl: SIGN('toc-do-toi-da-40.svg'),
    options: [
      'Không được chạy quá 40 km/h.',
      'Phải chạy tối thiểu 40 km/h.',
      'Chỉ áp dụng với ô tô, mô tô không bị giới hạn.',
    ],
    correctIndex: 0,
    explanation: 'Biển tốc độ tối đa áp dụng với mọi xe cơ giới, kể cả mô tô phân khối lớn.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình báo hiệu điều gì?',
    imageUrl: SIGN('nhuong-duong.svg'),
    options: [
      'Phải nhường đường cho xe trên đường ưu tiên.',
      'Được quyền đi trước.',
      'Cấm đi thẳng.',
    ],
    correctIndex: 0,
    explanation: 'Biển W.208 "Giao nhau với đường ưu tiên": giảm tốc và nhường đường.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Sa hình',
    content: 'Xe mô tô phân khối lớn khi vượt xe tải trên đường trường cần chú ý gì?',
    options: [
      'Quan sát gương và điểm mù của xe tải, báo hiệu rõ ràng, vượt dứt khoát về bên trái khi an toàn.',
      'Vượt sát đuôi xe tải cho nhanh.',
      'Vượt bên phải cho tiện.',
    ],
    correctIndex: 0,
    explanation: 'Xe tải có điểm mù lớn — phải báo hiệu sớm, quan sát kỹ và vượt trái dứt khoát khi đủ an toàn.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Sa hình',
    content: 'Khi chạy xe tốc độ cao gặp chướng ngại vật bất ngờ, thao tác nào đúng?',
    options: [
      'Giữ chắc tay lái, phanh cả hai phanh nhịp nhàng, không phanh gấp bánh trước.',
      'Bóp chặt phanh trước hết cỡ.',
      'Buông tay lái để nhảy khỏi xe.',
    ],
    correctIndex: 0,
    explanation: 'Phanh gấp bánh trước ở tốc độ cao dễ trượt ngã; phải phanh phối hợp cả hai bánh.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Tổ chức đua xe mô tô trái phép trên đường bộ bị xử lý như thế nào?',
    options: [
      'Bị nghiêm cấm, xử lý hình sự theo quy định pháp luật.',
      'Được phép ngoài giờ cao điểm.',
      'Chỉ bị phạt hành chính nhẹ.',
    ],
    correctIndex: 0,
    explanation: 'Đua xe, tổ chức đua xe trái phép là hành vi bị nghiêm cấm, có thể bị truy cứu trách nhiệm hình sự.',
    isCritical: true,
  },
  {
    classCode: 'A2',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Người lái mô tô phân khối lớn nẹt pô, rú ga liên tục trong khu dân cư thể hiện điều gì?',
    options: [
      'Hành vi thiếu văn hóa, gây tiếng ồn, bị nghiêm cấm.',
      'Cách cảnh báo an toàn cho người xung quanh.',
      'Quyền tự do cá nhân.',
    ],
    correctIndex: 0,
    explanation: 'Rú ga liên tục trong khu dân cư là hành vi bị cấm và thiếu văn hóa giao thông.',
    isCritical: false,
  },
  {
    classCode: 'A2',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Khi chở người ngồi sau trên mô tô phân khối lớn, người lái cần yêu cầu người ngồi sau làm gì?',
    options: [
      'Đội mũ bảo hiểm cài quai đúng cách, ngồi ổn định, bám chắc, không đùa nghịch.',
      'Ngồi tự do thoải mái.',
      'Chỉ cần đội mũ khi đi đường dài.',
    ],
    correctIndex: 0,
    explanation: 'Người ngồi sau phải đội mũ bảo hiểm đạt chuẩn và ngồi an toàn, ổn định.',
    isCritical: false,
  },

  /* ================= A3 (8 câu) ================= */
  {
    classCode: 'A3',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Giấy phép lái xe hạng A3 cấp cho người điều khiển loại xe nào?',
    options: [
      'Xe mô tô ba bánh và các loại xe quy định cho hạng A1.',
      'Chỉ xe ô tô tải nhỏ.',
      'Xe mô tô hai bánh trên 175cc.',
    ],
    correctIndex: 0,
    explanation: 'A3: xe mô tô ba bánh, xe lam, xích lô máy và các xe hạng A1.',
    isCritical: false,
  },
  {
    classCode: 'A3',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Xe mô tô ba bánh chở hàng phải xếp hàng hóa như thế nào?',
    options: [
      'Gọn gàng, chằng buộc chắc chắn, không vượt quá kích thước và trọng tải cho phép.',
      'Chở càng nhiều càng tốt để tiết kiệm chuyến.',
      'Chỉ cần buộc sơ nếu đi gần.',
    ],
    correctIndex: 0,
    explanation: 'Hàng hóa phải xếp gọn, chằng buộc chắc, đúng kích thước và trọng tải quy định.',
    isCritical: false,
  },
  {
    classCode: 'A3',
    categoryName: 'Khái niệm và quy tắc',
    content: 'Người lái xe mô tô ba bánh có nồng độ cồn trong máu khi lái xe bị xử lý ra sao?',
    options: [
      'Bị nghiêm cấm điều khiển phương tiện, xử phạt theo quy định.',
      'Được lái nếu đi chậm.',
      'Chỉ cấm vào ban đêm.',
    ],
    correctIndex: 0,
    explanation: 'Cấm tuyệt đối với mọi loại phương tiện cơ giới, kể cả mô tô ba bánh.',
    isCritical: true,
  },
  {
    classCode: 'A3',
    categoryName: 'Biển báo giao thông',
    content: 'Biển báo trong hình có hiệu lực với xe mô tô ba bánh không?',
    imageUrl: SIGN('cam-nguoc-chieu.svg'),
    options: [
      'Có — cấm mọi phương tiện đi ngược chiều, kể cả mô tô ba bánh.',
      'Không — chỉ cấm ô tô.',
      'Chỉ cấm vào giờ cao điểm.',
    ],
    correctIndex: 0,
    explanation: 'Biển "Cấm đi ngược chiều" có hiệu lực với mọi phương tiện cơ giới và thô sơ (trừ xe ưu tiên).',
    isCritical: false,
  },
  {
    classCode: 'A3',
    categoryName: 'Biển báo giao thông',
    content: 'Gặp biển báo trong hình, người lái xe ba bánh phải làm gì?',
    imageUrl: SIGN('vong-xuyen.svg'),
    options: [
      'Đi theo chiều vòng xuyến, nhường đường cho xe từ bên trái.',
      'Đi thẳng qua tâm vòng xuyến.',
      'Quay đầu xe.',
    ],
    correctIndex: 0,
    explanation: 'Biển R.303: đi theo vòng xuyến và nhường xe đang lưu thông trong vòng xuyến (bên trái).',
    isCritical: false,
  },
  {
    classCode: 'A3',
    categoryName: 'Sa hình',
    content: 'Xe ba bánh chở hàng cồng kềnh khi qua nơi giao nhau cần chú ý gì?',
    options: [
      'Giảm tốc độ, quan sát kỹ, chú ý bán kính quay vòng lớn hơn xe hai bánh.',
      'Đi nhanh qua giao lộ để tránh cản trở.',
      'Nhấn còi liên tục yêu cầu nhường đường.',
    ],
    correctIndex: 0,
    explanation: 'Xe ba bánh cồng kềnh, quay vòng rộng — phải giảm tốc và quan sát kỹ khi qua giao lộ.',
    isCritical: false,
  },
  {
    classCode: 'A3',
    categoryName: 'Sa hình',
    content: 'Khi xuống dốc dài, người lái xe ba bánh chở hàng nên làm gì?',
    options: [
      'Về số thấp, phanh động cơ kết hợp phanh chân, không thả trôi.',
      'Tắt máy thả trôi để tiết kiệm xăng.',
      'Rà phanh liên tục suốt con dốc.',
    ],
    correctIndex: 0,
    explanation: 'Xuống dốc dài phải dùng số thấp để hãm bằng động cơ; thả trôi hoặc rà phanh liên tục rất nguy hiểm.',
    isCritical: true,
  },
  {
    classCode: 'A3',
    categoryName: 'Đạo đức và văn hóa giao thông',
    content: 'Người lái xe ba bánh dừng xe bốc xếp hàng hóa giữa lòng đường gây cản trở giao thông là hành vi như thế nào?',
    options: [
      'Vi phạm quy tắc giao thông, thiếu văn hóa, có thể bị xử phạt.',
      'Bình thường vì xe chở hàng được ưu tiên.',
      'Chấp nhận được nếu bốc xếp nhanh.',
    ],
    correctIndex: 0,
    explanation: 'Dừng đỗ, bốc xếp hàng giữa lòng đường gây cản trở giao thông là vi phạm và thiếu văn hóa.',
    isCritical: false,
  },
];

module.exports = { licenseClasses, categories, questions };
